# Generated by Django 4.2.7 on 2024-01-22 20:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_rename_user_userprofile_user_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='academicdegree',
            name='degree_designation',
            field=models.CharField(help_text='The class of degree you attained or are in the process of attaining.', max_length=50),
        ),
        migrations.AlterField(
            model_name='activity',
            name='activity',
            field=models.CharField(blank=True, help_text='This should represent a compoetitive or lesure activity you enjoy on your free time.', max_length=40, null=True),
        ),
        migrations.AlterField(
            model_name='careergoal',
            name='career_goal',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='about',
            field=models.TextField(blank=True, max_length=1000, null=True),
        ),
    ]
