# Generated by Django 4.2.7 on 2024-01-22 20:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_alter_academicdegree_degree_designation_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='academicdegree',
            old_name='user_id',
            new_name='user',
        ),
        migrations.AlterField(
            model_name='technicalskill',
            name='skill',
            field=models.CharField(help_text='This skill could be a language, framework or field specific skill', max_length=40),
        ),
        migrations.AlterField(
            model_name='university',
            name='university_name',
            field=models.CharField(help_text='University or Institution that provided a qualification', max_length=50),
        ),
    ]
