# Generated by Django 4.2.7 on 2024-01-22 20:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0004_rename_user_id_academicdegree_user_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='activity',
            old_name='user_id',
            new_name='user',
        ),
        migrations.RenameField(
            model_name='careergoal',
            old_name='user_id',
            new_name='user',
        ),
        migrations.RenameField(
            model_name='occupation',
            old_name='user_id',
            new_name='user',
        ),
        migrations.RenameField(
            model_name='technicalskill',
            old_name='user_id',
            new_name='user',
        ),
        migrations.RenameField(
            model_name='userprofile',
            old_name='user_id',
            new_name='user',
        ),
    ]
