# Generated by Django 4.2.7 on 2024-01-22 21:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0005_rename_user_id_activity_user_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='occupation',
            name='company',
            field=models.CharField(default='not available', max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='academicdegree',
            name='field_of_study',
            field=models.CharField(help_text='The broad degree field or the focus you wish to represent.', max_length=100),
        ),
        migrations.AlterField(
            model_name='academicdegree',
            name='graduation_date',
            field=models.DateField(help_text='Date of graduation or expected graduation.'),
        ),
        migrations.AlterField(
            model_name='activity',
            name='activity',
            field=models.CharField(blank=True, help_text='This should represent a competitive or leisure activity you enjoy on your free time.', max_length=40, null=True),
        ),
        migrations.CreateModel(
            name='JobDescription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job_description', models.TextField(blank=True, null=True)),
                ('occupation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.occupation')),
            ],
        ),
        migrations.CreateModel(
            name='Accomplishments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('accomplishments', models.TextField(blank=True, help_text='Projects finished, awards attained or things you are proud of.', null=True)),
                ('occupation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.occupation')),
            ],
        ),
    ]
