# Generated by Django 4.2.7 on 2024-01-22 21:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0006_occupation_company_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Accomplishments',
            new_name='Accomplishment',
        ),
        migrations.RenameField(
            model_name='accomplishment',
            old_name='accomplishments',
            new_name='accomplishment',
        ),
    ]
