# Generated by Django 4.2.7 on 2024-01-23 04:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0007_rename_accomplishments_accomplishment_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='technicalskill',
            name='skill_icon',
            field=models.FileField(blank=True, default=None, null=True, upload_to='static/images'),
        ),
    ]
