# Generated by Django 4.2.7 on 2024-01-23 21:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0009_alter_technicalskill_skill_icon'),
    ]

    operations = [
        migrations.AlterField(
            model_name='technicalskill',
            name='skill_icon',
            field=models.ImageField(blank=True, help_text='this is not a required field. If no image is provided then a text display of the skill will be used.', null=True, upload_to='static/images'),
        ),
    ]
