# Generated by Django 4.2.7 on 2024-01-30 19:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0011_alter_technicalskill_skill_icon'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='profile_pic',
            field=models.ImageField(default='avatar.svg', help_text='this is a profile picture that will be displayed in the about section', null=True, upload_to=''),
        ),
    ]
