# Generated by Django 4.2.7 on 2024-01-30 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('image', models.ImageField(default='output.png', help_text='This picture demonstrates a visualization that was a result of your machine learning application', null=True, upload_to='')),
                ('project_description', models.TextField(blank=True, max_length=1000, null=True)),
                ('github_link', models.URLField(blank=True, max_length=400, null=True)),
                ('other_link', models.URLField(blank=True, max_length=400, null=True)),
            ],
        ),
    ]
